### ISSUE TITLE
Unexpected hkdf value

### ISSUE THREAD

**Issue by nononoy** [jtdowney/hkdf#1]
Hi. I'm trying to work with hkdf gem, but cant get expected value. I have 
`ikm = sqTU9FqHSsn33eOUphilgrozqJFb7BCdYPjI2m78QM0`
`salt = 4CQCKEyyOT_LysC17rsMXQ`
`Content-Encoding: auth\0`
`with HMAC-SHA-256.`
```
hkdf_prk = HKDF.new(ikm, :salt => salt, :info => 'Content-Encoding: auth\0')
prk = hkdf_prk.next_bytes(32)
Base64.urlsafe_encode64(prk)
 => "B9WE2A_HRlFfBUTxjiR1b2-odovQD3Yfs-ig25CmqPI="
```

But expected and correct value is `wV0sNSvW4PviyYKiaVTtPANmaSF7US5g3A5yj4bZeYw`.
I'm trying to implement web push payload encryption with hmac and hkdf. Here is the example values - https://tests.peter.sh/push-encryption-verifier/. Where is my mistake?

**Comment by jtdowney** [comment]
I don't know a whole lot about web push encryption but reading the associated RFCs it looks like you're missing a bit. First, it seems they're using the `auth_secret` per [the Pre-shared Authentication Secrets part of the RFC](https://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding-01#section-4.3).  Also, you're adding an escape character in a single quote string, which just takes the literal `\` and literal `0` in ruby. Here is the code I used to get the right value:

```ruby
require 'base64'
require 'hkdf'

ikm = Base64.urlsafe_decode64('sqTU9FqHSsn33eOUphilgrozqJFb7BCdYPjI2m78QM0')
auth_info = "Content-Encoding: auth\0"
auth_secret = Base64.urlsafe_decode64('r9kcFt8-4Q6MnMjJHqJoSQ')

hkdf = HKDF.new(ikm, salt: auth_secret, info: auth_info)
prk = hkdf.next_bytes(32)
puts Base64.urlsafe_encode64(prk)
```

That outputs `wV0sNSvW4PviyYKiaVTtPANmaSF7US5g3A5yj4bZeYw=`.

**Comment by nononoy** [comment]
I felt that I was mistaken in the details. Thank you so much!
