### ISSUE TITLE
Changelog for v1.0

### ISSUE THREAD

**Issue by toncid** [jtdowney/hkdf#2]
It would be very handy to see the v1.0 changelog. Having one would help solving breaking changes, such as this one: https://github.com/jtdowney/hkdf/commit/4e9576efe9616e27cbe447ee58c3708980b0665e

Have there been any other breaking changes?

**Comment by jtdowney** [comment]
There is no changelog but that is exactly why I added an upgrading guide at https://github.com/jtdowney/hkdf/blob/main/UPGRADING.md

**Comment by toncid** [comment]
Aaaah, sorry, missed that one. Thanks!
